language: python
python:
  - "2.7"
install:
  - pip install pygments lxml setuptools --upgrade
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update
script:
  - bikeshed spec specification/common/index.bs specification/common/index.html
  - bikeshed spec specification/generic/index.bs specification/generic/index.html
  - bash ./deploy.sh
env:
  global:
  # Fingerprint: ae:ba:fa:2d:59:87:59:f1:4d:cd:33:c9:ce:87:44:fb
  - ENCRYPTION_LABEL: "56ee7be007ee"
  - COMMIT_AUTHOR_EMAIL: "adrian@holovaty.com"
