# Generated by Django 3.1.5 on 2021-01-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0002_exampledocumentelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spec.datatype')),
            ],
            options={
                'db_table': 'data_type_options',
            },
        ),
    ]
