# Generated by Django 3.1.5 on 2021-03-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0004_documentformat_exampledocumentcomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampledocumentcomparison',
            name='position',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
