# Generated by Django 3.1.5 on 2021-03-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0005_exampledocumentcomparison_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLAttributeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'db_table': 'xml_attribute_groups',
            },
        ),
        migrations.AlterField(
            model_name='xmlattribute',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spec.xmlelement'),
        ),
        migrations.AddField(
            model_name='xmlattribute',
            name='attribute_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spec.xmlattributegroup'),
        ),
    ]
