# Generated by Django 3.1.5 on 2021-03-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0006_attribute_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xmlattributegroup',
            options={'verbose_name': 'XML attribute group', 'verbose_name_plural': 'XML attribute groups'},
        ),
        migrations.AddField(
            model_name='xmlelement',
            name='attribute_groups',
            field=models.ManyToManyField(to='spec.XMLAttributeGroup'),
        ),
    ]
