# Generated by Django 4.1.5 on 2023-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0031_json_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonobject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
