# Generated by Django 4.1.5 on 2023-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0032_jsonobject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonobjectrelationship',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
