<pre class="metadata">
Status: LD
Title: MNX Draft Specification
Shortname: cwmnx-draft
Level: 1
Editor: Joe Berkovitz, Noteflight / Hal Leonard Corporation
Abstract: A draft specification for the MNX music notation document format.
Markup Shorthands: markdown yes
Repository: w3c/mnx
!Participate: <a href="https://github.com/w3c/mnx/issues/new">File an issue</a> (<a href="https://github.com/w3c/mnx/issues">open issues</a>)
</pre>
