<section>
<h2 id="infrastructure">Infrastructure</h2>

<h3 id="common-syntax">Syntax</h3>
<h4 id="note-values">Note Values</h4>

<!-- 
    /4, /8, /16, etc. for fractional note values (= quarter, eighth, ...)
    ./4, ../4 for dotted values (= 3/8, 7/16, ...)
    /1 = whole note (by convention, since *1 could make sense)
    *2, *4 (breve, longa, ...)
    ./1, .*2: dotted long-value notes
 -->
</section>
