# Generated by Django 3.1.5 on 2021-03-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0009_auto_20210314_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlelement',
            name='content_data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spectools.datatype'),
        ),
    ]
