# Generated by Django 3.1.5 on 2021-03-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0010_xmlelement_content_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='max_value',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='datatype',
            name='min_value',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
