# Generated by Django 3.1.5 on 2021-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0013_siteoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlelement',
            name='children_type',
            field=models.SmallIntegerField(choices=[(1, 'Unordered'), (2, 'Sequence'), (3, 'Choice')], default=1, help_text='This specifies the requirment for child elements.'),
        ),
        migrations.AlterField(
            model_name='exampledocument',
            name='image_url',
            field=models.CharField(blank=True, help_text='Path to the image within the doctools/media directory, e.g., "/static/examples/test.jpg".', max_length=300),
        ),
    ]
