# Generated by Django 3.1.5 on 2021-03-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0017_xmlschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(help_text='Make sure it starts and ends with slashes.', max_length=150)),
                ('order', models.SmallIntegerField()),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spectools.xmlschema')),
            ],
            options={
                'db_table': 'static_page_collections',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(help_text='Make sure it starts and ends with slashes.', max_length=150)),
                ('order', models.SmallIntegerField()),
                ('content', models.TextField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectools.staticpagecollection')),
            ],
            options={
                'db_table': 'static_pages',
            },
        ),
    ]
