# Generated by Django 3.1.5 on 2021-04-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0020_datatype_min_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spectools.xmlschema'),
            preserve_default=False,
        ),
    ]
