# Generated by Django 3.1.5 on 2021-04-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0021_datatype_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlelement',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='This is displayed next to the element name in parentheses in order to disambiguate it. E.g., "timewise" for <part>', max_length=80),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='order',
            field=models.SmallIntegerField(help_text='This is the order of the page within the collection. Ordering is ascending.'),
        ),
    ]
