# Generated by Django 3.1.5 on 2021-04-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0022_auto_20210413_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlattributegroup',
            name='description',
            field=models.TextField(blank=True, help_text='This is not displayed publicly.'),
        ),
    ]
