# Generated by Django 3.1.5 on 2021-04-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0025_datatypeoption_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteoptions',
            name='sidebar_html',
            field=models.TextField(blank=True, help_text='Raw HTML to put into the left sidebar of each page.'),
        ),
    ]
