# Generated by Django 3.1.5 on 2021-05-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0027_auto_20210427_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampledocumentelement',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spectools.xmlelement'),
        ),
        migrations.AlterField(
            model_name='exampledocument',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spectools.xmlschema'),
        ),
    ]
