# Generated by Django 3.1.5 on 2021-03-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0008_auto_20210313_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xmlrelationship',
            options={'verbose_name': 'XML relationship', 'verbose_name_plural': 'XML relationships'},
        ),
        migrations.AddField(
            model_name='xmlelement',
            name='base_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spectools.xmlelement'),
        ),
        migrations.AddField(
            model_name='xmlelement',
            name='is_abstract_element',
            field=models.BooleanField(default=False),
        ),
    ]
