# Generated by Django 3.1.5 on 2021-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0011_auto_20210316_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlelement',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Check this only for the root element(s) in the schema.'),
        ),
    ]
