# Generated by Django 3.1.5 on 2021-03-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0015_auto_20210329_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, help_text='HTML tags are allowed here.'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='description',
            field=models.TextField(blank=True, help_text='HTML tags are allowed here.'),
        ),
        migrations.AlterField(
            model_name='datatypeoption',
            name='description',
            field=models.TextField(blank=True, help_text='HTML tags are allowed here.'),
        ),
        migrations.AlterField(
            model_name='xmlattribute',
            name='description',
            field=models.TextField(blank=True, help_text='HTML tags are allowed here.'),
        ),
        migrations.AlterField(
            model_name='xmlelement',
            name='description',
            field=models.TextField(blank=True, help_text='HTML tags are allowed here.'),
        ),
    ]
