# Generated by Django 3.1.5 on 2021-03-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0016_auto_20210329_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'XML schema',
                'verbose_name_plural': 'XML schemas',
                'db_table': 'xml_schemas',
            },
        ),
        migrations.RunSQL([
            """
            INSERT INTO xml_schemas
                (name, slug)
            VALUES
                ('MNX', 'mnx')
            """
        ]),
        migrations.AlterField(
            model_name='exampledocument',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xmlelement',
            name='slug',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='exampledocument',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spectools.xmlschema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xmlelement',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spectools.xmlschema'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='exampledocument',
            unique_together={('schema', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='xmlelement',
            unique_together={('schema', 'slug')},
        ),
    ]
