# Generated by Django 3.1.5 on 2021-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0019_datatype_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='min_length',
            field=models.IntegerField(blank=True, help_text='This can be used for string types.', null=True),
        ),
    ]
