# Generated by Django 3.1.5 on 2021-04-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0023_xmlattributegroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlattributegroup',
            name='child_groups',
            field=models.ManyToManyField(blank=True, to='spectools.XMLAttributeGroup'),
        ),
    ]
