# Generated by Django 3.1.5 on 2021-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectools', '0024_xmlattributegroup_child_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypeoption',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
